# Generated by Django 4.1.6 on 2023-02-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_customer_alter_note_description_alter_note_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='tipe',
        ),
        migrations.AddField(
            model_name='note',
            name='type',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
